[build]
nixPkgs = ["php82", "php82Extensions.curl", "php82Extensions.mbstring", "php82Extensions.pdo_mysql"]

[deploy]
start = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
